version: "3"

services:
    db:
        image: mysql:8.3
        restart: unless-stopped
        hostname: db
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        volumes:
            - "db:/var/lib/mysql"

    app:
        build:
            context: ./build/app
            dockerfile: Dockerfile
        image: fop2/app:2.31.39
        environment:
            MYSQL_DATABASE_FOP2: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_HOST: 'db'
            MYSQL_PORT: 3306
        ports:
            - "4445:4445"
            - "8085:80"

volumes:
  db:
    driver: local